language: c
addons:
    apt:
        packages:
            - libelf-dev
            - glibc-dev
            - ninja-build
            - gperf
sudo: false
compiler:
    - clang
    - gcc
env:
    matrix:
        - COVERAGE=true
        - COVERAGE=false
install:
    - $COVERAGE && pip install --user cpp-coveralls || true
script:
    - export PATH="${PATH}:${HOME}/.local/bin"
    - $COVERAGE && export CC="${CC} -fprofile-arcs -ftest-coverage -O0 -g" || true
    - ./configure --objdir=out --enable-checks --enable-bundled-lua --enable-bundled-libdwarf && ninja && ./run-tests --verbose --output=tap
after_success:
    - $COVERAGE && coveralls --exclude out --exclude --gcov-options '\-lp' || true
