language: c
compiler:
    - clang
    - gcc
env:
    matrix:
        - COVERAGE=true
        - COVERAGE=false
install:
    - $COVERAGE && sudo pip install cpp-coveralls || true
script:
    - $COVERAGE && export CC="${CC} -fprofile-arcs -ftest-coverage -O0 -g" || true
    - ./configure --objdir=out --enable-checks --enable-bundled-lua --enable-bundled-libdwarf
    - make V=1
    - ./run-tests --verbose
after_success:
    - $COVERAGE && coveralls --exclude lua --exclude lua-$LUA_VER --gcov-options '\-lp' || true
