language: c
compiler:
    # - clang
    - gcc
env:
    matrix:
        - COVERAGE=true
        - COVERAGE=false
install:
    - sudo apt-get install -y libelf-dev ninja-build gperf
    - $COVERAGE && sudo pip install cpp-coveralls || true
script:
    - $COVERAGE && export CC="${CC} -fprofile-arcs -ftest-coverage -O0 -g" || true
    - ./configure --objdir=out --enable-checks --enable-bundled-lua --enable-bundled-libdwarf && ninja && ./run-tests --verbose --output=tap
after_success:
    - $COVERAGE && coveralls --exclude out --exclude --gcov-options '\-lp' || true
