#! /bin/sh
#
# Usage: $0 lua-binary script.lua objdir outfile
#

pushd "$(dirname "$1")" &> /dev/null
luadir=$(pwd)
popd &> /dev/null

mkdir -p "$3" "$(dirname "$4")"
curdir=$(pwd)

pushd "$(dirname "$2")" &> /dev/null
script="$(pwd)/$(basename "$2")"
popd &> /dev/null

pushd "$3" &> /dev/null
objdir=$(pwd)
popd &> /dev/null

cat > "$4" <<EOF
#! /bin/sh
set -e
cd '${objdir}'
exec '${luadir}/$(basename "$1")' '${script}' "\$@"
EOF
chmod +x "$4"
