#! /bin/sh
#
# run-tests
# Copyright (C) 2015 Adrian Perez <aperez@igalia.com>
#
# Distributed under terms of the MIT license.
#

# Obtain the working directory and the directory where this scripts resides,
# which then can be used to find the test harness and the needed binaries.
curdir=$(pwd)
cd "$(dirname "$0")/.."
eoldir=$(pwd)

if ! test -r build.conf
then
	echo "build.conf not found. Have you run ./configure?" 1>&2
	exit 1
fi

luaexe=$(sed -e 's/^system_lua_bin[[:space:]]*=[[:space:]]*\(.*\)$/\1/p' -e 'd' build.conf)
objdir=$(sed -e 's/^obj[[:space:]]*=[[:space:]]*\(.*\)$/\1/p' -e 'd' build.conf)
cd "${objdir}"
objdir=$(pwd)

if test "x${luaexe}" = "x"
then
	luaexe="${objdir}/lua"
fi

for file in libtest.so eol.so testutil.so "${luaexe}"
do
	if ! test -r "${file}"
	then
		echo "File not found: ${file}" 1>&2
		echo "Have you run 'ninja' or 'make'?" 1>&2
		exit 1
	fi
done

export EOL_LUA_EXE="${luaexe}"
export LUA_INIT="@${eoldir}/tools/harness-assert.lua"
exec "${luaexe}" "${eoldir}/tools/harness.lua" "${eoldir}" "${curdir}" "$@"
